name: AF-test1
favicon: null
layout_spectrum: 0.1947945482097566
typography_spectrum: 0.39926876686513424
title: "Andrew's Grid experience"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.7379869287833571
  lightness: 0.8184618053492159
  saturation: 0.8732557783368975
  rhythmicContrast: 0.8368299405556172
purpose: []
